pfield_manager:
  ros__parameters:
    timer_frequency: 100.0 # [Hz]
    attractive_gain: 1.0 # [Ns/m]
    rotational_attractive_gain: 0.7 # [Ns/m]
    repulsive_gain: 20.0 # [Ns/m]
    max_force: 10.0 # [N]
robot_parser:
  ros__parameters:
    timer_frequency: 50.0 # [Hz]