name: Build, and Test ROS Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test_ros2:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Install Linux dependencies
        run: apt-get update && apt-get install -y libeigen3-dev liburdfdom-dev libfcl-dev libccd-dev libassimp-dev

      - name: Install ROS apt libraries
        run: |
          apt-get install -y ros-jazzy-pinocchio
          apt-get install -y ros-jazzy-urdf

      - name: Configure Git Credentials
        run: |
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Build and run tests
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: potential_fields pfield_library
          target-ros2-distro: jazzy
