name: Build, and Test ROS Packages

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  build_and_test_ros2:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Install Eigen3
        run: apt-get update && apt-get install -y libeigen3-dev
        
      - name: Build and run tests
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: potential_fields
          target-ros2-distro: jazzy
        env:
          ROS_REPOS_TOKEN: ${{ secrets.GH_PAT }}
